engine: redis
redis_address: 127.0.0.1:6969
admin: true
# prometheus: true

# Secrets
token_hmac_secret_key: bruh
admin_password: meme
admin_secret: lol
api_key: epic
# generate these with ./centrifugo genconfig (https://centrifugal.dev/docs/getting-started/quickstart)

http3: true
tls: true
tls_cert: cert.pem
tls_key: cert-key.pem

allow_subscribe_for_client: true
allow_publish_for_subscriber: true
allow_history_for_subscriber: true
allow_presence_for_subscriber: true

webtransport: true

allowed_origins:
  - "*" # not secure

namespaces:
  - name: "chat"
    publish: true
    subscribe_to_publish: true
    history_size: 100
    history_ttl: 100h
    recover: true
    presence: true
    join_leave: true
    force_push_join_leave: true

    allow_subscribe_for_client: true
    allow_publish_for_subscriber: true
    allow_history_for_subscriber: true
    allow_presence_for_subscriber: true

      #  - name: "logs"
      #   anonymous: true
      #    history_size: 1000
      #    history_ttl: 10000h
