export const splashes = [
	"Now with more EVERYTHING!",
	"What happpened to DocSocial?",
	"Now with extra protein!",
	"They can't ban us. 🔨",
	"📄 Remember to read the ToS!",
	"Built with Svelte!",
	"Cybernetically enhanced!",
	"Now in <strong>SHOCKING</strong> 2-D!",
	"One in a million!",
	"Coming soon! 🔜",
	"End-to-end encrypted!",
	"It's anonymous and FREE!",
	"Better than Hangouts!",
	"Serving suggestion",
	"53 GitHub commits!",
	"undefined",
	"[object Object]",
	"Accepts payment via propane!",
	"Happy birthday! 🎉",
	"Ratio, touch grass",
	"<strong><em>Even less XSS!</em></strong>",
	"5.72 Gibibytes!",
	"Not stolen from Minecraft!",
	"Doesn't use <center>!",
	"It's not a bug, it's a feature!",
	"",
	"💯",
	"Welcome!",
	"Updated and supported indefinitely! 🕝",
	"Series of tubes!",
	"The world's most resilient chat app.",
	"Sixty-four bits!",
	"Doesn't use cookies! 🍪",
	"Didn't start the fire! 🔥",
	"New and improved recipe!",
	"Warranty not included.",
	"Perfect lighthouse report! ",
	"Not sponsored by RAID: Shadow Legends!",
	"🍌A source of Potassium!",
	"One of your five-a-day! 5️⃣",
	"Better than Half-life 3!",
	"No risk of Salmonella!",
	"Out of beta testing!",
	"Three billion devices!",
	"Upgraded to C++11!",
	"Remember to wear a mask! 😷",
	"💉 Get vaccinated!",
	"78 Billion lines of code!",
	"Look behind you.",
	"No longer Object-Oriented!",
	"We � Unicode!",
	"Start Wandows Ngrmadly.",
	"Safe Mode wath Fetwgrkifg!",
	"⌨️ Typed in Dvorak!",
	"Reactive state management!",
	"Hot module replacement!",
	"Avoid 3,4-Methylenedioxymethamphetamine!",
	"Eighty megabytes and constantly swapping!",
	"npm run dev",
	"No longer a thing!",
	"Powered by StackOverflow!",
	"Thanks, GitHub Copilot!",
	"Uses no legacy code!",
	"Supports Internet Explorer 12!",
	"Runs on Windows XP! 🪟",
	"Runs in Adobe Flash!",
	"eChat on top!",
	"Exactly 0% TypeScript!",
	"Always trust the client!",
	"Green theme = best theme",
	"🐧 GNU/Linux compatible!",
	"Loves you! ❤️",
	"Added Vitamin E! 💊",
	"Still works!",
	"Not dead yet!",
	"Is your fridge running?",
	"Totally not a virus! 🦠",
	"Find all the Easter eggs! 🥚",
	"Does not use PHP!",
	"👍 Yeah 👍",
	"ඞ GET OUT OF MY HEAD",
	"w̷̖̫̋̐̂̈́͑̔̉a̸̭̠͕͚̓͂ͅţ̶̪́ć̶̨͕͔͔͈̈̕h̸̗͇̮̮͔̩̀̇̆͆̉͝ ̶̣̭̻̱̺̃ő̴̼͍̮͙̞͕̈̌̑̃́͗u̵̫̪͆̆̎̉ͅṭ̵̨̅͑̋̈̓̑̕͜.̶̣͓̩͓̉.̴̧̢̯̱̭̈́̇̈́̊́̉͝",
	"Closed source (for now).",
	"Wait until eChat 2!",
	"A source of 2-methyl-1,3,5-trinitrobenzene! 💥",
	"Not a source of neurotoxins!",
	"🐛 Report any bugs!",
	"💧 Remember to stay hydrated!",
	"Net neutrality!",
	"Internet connection is required!",
	"Respects your privacy! 🙈",
	"⚡ Lightning fast!",
	"3.141592653589793238462643383279502884197169",
	"Unlimited edition!!",
	"Over 0 million products sold!",
	"📈 Buy eChat stock!",
	"Batteries included!",
	"Single-threaded!",
	"eChat: The Movie: The Game, coming soon.",
	"Actively developed!",
	"Reddit moment",
	"We did it!",
	"⏱️ Developed in record time!",
	"Not quite finished yet!",
	"As seen on TV! 📺",
	"Legacy APIs!",
	"Does not include splash texts!",
	"Uses half as much energy as competitors! 💡",
	"Compiled, not interpreted!",
	"You're doing great!",
	"You got this! 💪",
	"Buy the eChat NFT!",
	"⬆️ Surpasses your expectations!",
	"Just as good as IRL interactions! 💬",
	"Way too linear!",
	"Adheres to the Geneva Convention!",
	"Reduces productivity! 📗",
	"Download more RAM!",
	"YOU WIN! 🏆",
	"😎 <em>Pretty cool...<em>",
	"A bit better than DocSocial!",
	"<a>How to trick an idiot</a>",
	"🧑‍💻 Learn programming!",
	"130 Words per minute!",
	"Please remain calm. 🧘",
	"💖",
	"Tastes like chicken! 🍗",
	"Turing completeness...?",
	"🥧 Excited for pi day!",
	"Is today Friday the 13th?",
	"📊 Data analysis!",
	"Increased CPU power!",
	"This statement is false.",
	"👍 Without a doubt!",
	"Bogos binted? 👽",
	"Epic AND Awesome!",
	"Sear your eyes with Light Theme!",
	"No longer supported by Meta! Ⓜ️",
	"Part of the Metaverse!!",
	"Owned by Mark Zuckerberg!",
	"🅱️Chat 👌😂",
	"Have a great day!",
	"6.28% extra entropy!",
	"Save the planet! 🌎",
	"👋 Hello, world!",
	"Caught in 4k 🎥",
	"Memory leaks!",
]