export const splashes = [
		"Now with more EVERYTHING!",
		"What happpened to DocSocial?",
		"Now with extra protein!",
		"They can't ban us.",
		"Remember to read the ToS!",
		"Built with Svelte!",
		"Cybernetically enhanced!",
		"Now in SHOCKING 2-D!",
		"One in a million!",
		"Coming soon!",
		"End-to-end encrypted!",
		"It's anonymous and FREE!",
		"Better than Hangouts!",
		"Serving suggestion",
		"45 GitHub commits!",
		"undefined",
		"[object Object]",
		"Accepts payment via propane!",
		"Happy birthday!",
		"Ratio, touch grass",
		"Even less XSS!",
		"5.72 Gibibytes!",
		"Not stolen from Minecraft!",
		"Doesn't use <center>!",
		"It's not a bug, it's a feature!",
		"",
		"Welcome!",
		"Updated and supported indefinitely!",
		"Series of tubes!",
		"World's most resilient chat app.",
		"Sixty-four bits!",
		"Doesn't use cookies!",
		"Didn't start the fire!",
		"New and improved recipe!",
		"Warranty not included.",
		"Perfect lighthouse report!",
		"Not sponsored by RAID: Shadow Legends!",
		"A source of Potassium!",
		"One of your five-a-day!",
		"Better than Half-life 3!",
		"No risk of Salmonella!",
		"Out of beta testing!",
		"Three billion devices!",
		"Upgraded to C++11!",
		"Remember to wear a mask!",
		"Get vaccinated!",
		"78 Billion lines of code!",
		"Look behind you.",
		"No longer Object-Oriented!",
		"We � Unicode!",
		"Start Wandows Ngrmadly.",
		"Safe Mode wath Fetwgrkifg!",
		"Typed in Dvorak!",
		"Reactive state management!",
		"Hot module replacement!",
		"Avoid 3,4-Methylenedioxymethamphetamine!",
		"Eighty megabytes and constantly swapping!",
		"npm run dev",
		"No longer a thing!",
		"Powered by StackOverflow!",
		"Thanks, GitHub Copilot!",
	]